import gql from "graphql-tag";

export const GET_USERS = gql`
  query getUsers {
    users(
      order_by: {id: asc}
    )
     {
      name
      id
      email
    }
  }
`;
export const GET_PRODUCTS = gql`
query getProducts {
  products(
    order_by: {id: asc}
  )
   {
    id
    title
    price
    description
    user_id
  }
}
`;
